# .github/workflows/ci-main.yaml - DISABLED
# This workflow has been disabled to avoid conflicts with CodeQLcustom
name: CodeQL-DISABLED

# Disabled: workflow_dispatch only (manual trigger only, will not run automatically)
on:
  workflow_dispatch:
    inputs:
      force_run:
        description: 'This workflow is disabled. Use CodeQLcustom instead.'
        required: true
        default: 'disabled'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  analyze:
    if: false  # This job will never run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: go, python
      - uses: github/codeql-action/analyze@v3
